# This is a basic workflow to help you get started with Actions

name: "Emscripten Build"

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk

    steps:
      - uses: actions/checkout@v2

      - name: Build # build the app in the emscripten container
        run: |
          mkdir -v -p build
          emscripten/emsdk em++ hello_world.cpp -o build/index.html

      - name: Install rsync 📚 # needed for `deploy to github pages` action
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: emscripten-build # The branch the action should deploy to.
          FOLDER: build/ # The folder the action should deploy.
